### ISSUE TITLE
"Scholars'" in Scholars' Lab is plural possessive

### ISSUE THREAD

**Issue by jeremyboggs** [scholarslab/makergrounds#1]
The map of makerspaces and the people image on the home page incorrectly label us as "Scholar's Lab".

**Comment by ammonshepherd** [comment]
Jason,

Can you edit this in the inDesign file? I should get that software...

**Comment by ghost** [comment]
Hey Ammon,

I just realized I used too much compression on that JPEG. Attached is a less compressed one with fewer artifacts.

-Jason

## 

Jason C. Bennett, MEd
Maker Space Specialist
Learning Design & Technology
The University of Virginia
College of Arts & Sciences
Wilson Hall
Charlottesville, VA 22904
Google Voice #: 434-535-2762

**Comment by ammonshepherd** [comment]
Replaced static map with a dynamic map using Mapbox
