### ISSUE TITLE
New People Network image

### ISSUE THREAD

**Issue by ammonshepherd** [scholarslab/makergrounds#3]
Can we put up the new People PDF just to get the basic changes in there?

**Comment by ammonshepherd** [comment]
Jason, 

I don't have Adobe products, yet. Can you export the new people network from inDesign to jpg?

**Comment by ghost** [comment]
Yup I'll do it as soon as I'm back from lunch.

On Sep 9, 2016 1:35 PM, Ammon Shepherd notifications@github.com wrote:

Jason,

I don't have Adobe products, yet. Can you export the new people network from inDesign to jpg?
